-- PawPing cumulative V7 migration. Safe to run repeatedly.
create extension if not exists pgcrypto;
create table if not exists public.location_events(id uuid primary key default gen_random_uuid(),cat_id uuid not null references public.cats(id) on delete cascade,source text not null check(source in ('finder','gps','manual')),latitude double precision not null check(latitude between -90 and 90),longitude double precision not null check(longitude between -180 and 180),accuracy_m double precision,battery_percent integer check(battery_percent between 0 and 100),message text,recorded_at timestamptz not null default now());
create table if not exists public.owner_alerts(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,cat_id uuid references public.cats(id) on delete cascade,kind text not null,title text not null,body text,read_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.tracker_devices(id uuid primary key default gen_random_uuid(),cat_id uuid not null references public.cats(id) on delete cascade,owner_id uuid not null references auth.users(id) on delete cascade,name text not null,token_hash text not null unique,is_active boolean not null default true,battery_percent integer,last_seen_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.geofences(id uuid primary key default gen_random_uuid(),cat_id uuid not null references public.cats(id) on delete cascade,owner_id uuid not null references auth.users(id) on delete cascade,name text not null,latitude double precision not null,longitude double precision not null,radius_m integer not null check(radius_m>=25),is_active boolean not null default true,created_at timestamptz not null default now());
alter table public.location_events enable row level security;alter table public.owner_alerts enable row level security;alter table public.tracker_devices enable row level security;alter table public.geofences enable row level security;
create or replace function public.owns_cat(p_cat uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.cats where id=p_cat and owner_id=auth.uid())$$;
do $$begin create policy "owners read locations" on public.location_events for select to authenticated using(public.owns_cat(cat_id));exception when duplicate_object then null;end$$;
do $$begin create policy "owners read alerts" on public.owner_alerts for select to authenticated using(owner_id=auth.uid());exception when duplicate_object then null;end$$;
do $$begin create policy "owners update alerts" on public.owner_alerts for update to authenticated using(owner_id=auth.uid());exception when duplicate_object then null;end$$;
do $$begin create policy "owners read devices" on public.tracker_devices for select to authenticated using(owner_id=auth.uid());exception when duplicate_object then null;end$$;
do $$begin create policy "owners read geofences" on public.geofences for select to authenticated using(owner_id=auth.uid());exception when duplicate_object then null;end$$;
do $$begin create policy "owners insert geofences" on public.geofences for insert to authenticated with check(owner_id=auth.uid() and public.owns_cat(cat_id));exception when duplicate_object then null;end$$;
grant select on public.location_events,public.owner_alerts,public.tracker_devices,public.geofences to authenticated;grant update on public.owner_alerts to authenticated;grant insert on public.geofences to authenticated;
create or replace function public.create_tracker_device(p_cat_id uuid,p_name text) returns text language plpgsql security definer set search_path=public,extensions as $$declare t text:=encode(gen_random_bytes(24),'hex');begin if not public.owns_cat(p_cat_id) then raise exception 'not owner';end if;insert into public.tracker_devices(cat_id,owner_id,name,token_hash) values(p_cat_id,auth.uid(),p_name,encode(digest(t,'sha256'),'hex'));return t;end$$;grant execute on function public.create_tracker_device(uuid,text) to authenticated;
create or replace function public.ingest_gps_location(p_token text,p_latitude double precision,p_longitude double precision,p_accuracy_m double precision default null,p_battery integer default null,p_recorded_at timestamptz default now()) returns uuid language plpgsql security definer set search_path=public,extensions as $$declare d public.tracker_devices;eid uuid;begin select * into d from public.tracker_devices where token_hash=encode(digest(p_token,'sha256'),'hex') and is_active=true;if d.id is null then raise exception 'invalid device token';end if;insert into public.location_events(cat_id,source,latitude,longitude,accuracy_m,battery_percent,recorded_at) values(d.cat_id,'gps',p_latitude,p_longitude,p_accuracy_m,p_battery,p_recorded_at) returning id into eid;update public.tracker_devices set last_seen_at=now(),battery_percent=p_battery where id=d.id;return eid;end$$;grant execute on function public.ingest_gps_location(text,double precision,double precision,double precision,integer,timestamptz) to anon,authenticated;
create or replace function public.on_finder_report() returns trigger language plpgsql security definer set search_path=public as $$declare oid uuid;cn text;begin select owner_id,name into oid,cn from public.cats where id=new.cat_id;insert into public.location_events(cat_id,source,latitude,longitude,accuracy_m,message,recorded_at) values(new.cat_id,'finder',new.latitude,new.longitude,new.accuracy_m,new.message,new.created_at);if oid is not null then insert into public.owner_alerts(owner_id,cat_id,kind,title,body) values(oid,new.cat_id,'found',cn||' was found',coalesce(new.message,'A finder shared a location.'));end if;return new;end$$;
drop trigger if exists trg_finder_report_v7 on public.finder_reports;create trigger trg_finder_report_v7 after insert on public.finder_reports for each row execute function public.on_finder_report();
