import {useRouter} from "next/router";
import {useEffect,useState} from "react";
import {supabase,ready} from "../../lib/supabase";
export default function PublicPet(){
 const {query}=useRouter();const [pet,setPet]=useState(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("I found this pet and it is safe.");const [result,setResult]=useState("");
 useEffect(()=>{if(!query.token||!supabase)return;(async()=>{const {data,error}=await supabase.from("cats").select("id,name,photo_url,age,color,temperament,health_note,status").eq("public_token",query.token).maybeSingle();setPet(data||null);setResult(error?error.message:"");setLoading(false)})();},[query.token]);
 function submit(){if(!navigator.geolocation){setResult("Location is not supported by this browser.");return;}setBusy(true);setResult("Requesting location permission...");navigator.geolocation.getCurrentPosition(async(position)=>{const {error}=await supabase.from("finder_reports").insert({cat_id:pet.id,latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy_m:position.coords.accuracy,message:message.trim()});setBusy(false);setResult(error?`Could not send report: ${error.message}`:"Thank you. The owner can now see this sighting.");},(error)=>{setBusy(false);setResult(`Location not shared: ${error.message}`);},{enableHighAccuracy:true,timeout:15000,maximumAge:0});}
 if(!ready)return <main className="shell"><section className="card">Setup missing.</section></main>;
 if(loading)return <main className="shell"><section className="card">Loading pet profile...</section></main>;
 if(!pet)return <main className="shell"><section className="card"><h1>Pet not found</h1><p>{result||"This tag is invalid or inactive."}</p></section></main>;
 return <main className="shell"><section className="hero">{pet.photo_url?<img src={pet.photo_url} alt={pet.name}/>:<span>🐈</span>}<b className={pet.status}>{pet.status}</b></section><section className="card joined"><p className="eyebrow">YOU FOUND</p><h1>{pet.name}</h1><p className="muted">{pet.temperament||"Please approach carefully."}</p><div className="facts"><div><small>COLOR</small><strong>{pet.color||"Not provided"}</strong></div><div><small>AGE</small><strong>{pet.age||"Not provided"}</strong></div></div>{pet.health_note&&<p className="notice"><b>Important:</b> {pet.health_note}</p>}<label>Message to owner</label><textarea value={message} maxLength={500} onChange={(event)=>setMessage(event.target.value)}/><button disabled={busy} onClick={submit}>{busy?"Getting location...":"📍 Report this sighting"}</button>{result&&<p className="notice">{result}</p>}<p className="privacy">Exact location is shared only after permission and is visible only to the pet owner.</p></section></main>;
}
