import {useEffect,useState} from "react";import Link from "next/link";import {supabase,isConfigured} from "../lib/supabase";
export default function Advanced(){const [session,setSession]=useState(null),[cats,setCats]=useState([]),[events,setEvents]=useState([]),[alerts,setAlerts]=useState([]),[devices,setDevices]=useState([]),[msg,setMsg]=useState(""),[selected,setSelected]=useState(null),[fence,setFence]=useState({cat_id:"",name:"Home",latitude:"",longitude:"",radius_m:250});
useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[]);useEffect(()=>{if(session)load()},[session]);
async function load(){const [c,e,a,d]=await Promise.all([supabase.from("cats").select("id,name"),supabase.from("location_events").select("*,cats(name)").order("recorded_at",{ascending:false}),supabase.from("owner_alerts").select("*,cats(name)").order("created_at",{ascending:false}),supabase.from("tracker_devices").select("*,cats(name)").order("created_at",{ascending:false})]);const er=[c,e,a,d].find(x=>x.error);if(er)setMsg(er.error.message);setCats(c.data||[]);setEvents(e.data||[]);setAlerts(a.data||[]);setDevices(d.data||[]);setSelected((e.data||[])[0]||null);if(!fence.cat_id&&c.data?.[0])setFence(x=>({...x,cat_id:c.data[0].id}))}
async function device(cat){const {data,error}=await supabase.rpc("create_tracker_device",{p_cat_id:cat.id,p_name:`${cat.name} GPS`});setMsg(error?error.message:`Copy this device token now. It is shown once: ${data}`);if(!error)load()}
async function saveFence(e){e.preventDefault();const {error}=await supabase.from("geofences").insert({...fence,owner_id:session.user.id,latitude:Number(fence.latitude),longitude:Number(fence.longitude),radius_m:Number(fence.radius_m)});setMsg(error?error.message:"Geofence saved.")}
async function read(id){await supabase.from("owner_alerts").update({read_at:new Date().toISOString()}).eq("id",id);load()}
function csv(){const rows=[["pet","source","latitude","longitude","accuracy_m","recorded_at"],...events.map(x=>[x.cats?.name||"",x.source,x.latitude,x.longitude,x.accuracy_m||"",x.recorded_at])];const s=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("
");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([s],{type:"text/csv"}));a.download="pawping-location-history.csv";a.click()}
if(!isConfigured)return <main className="shell"><section className="panel">Setup missing.</section></main>;if(!session)return <main className="shell"><section className="panel"><h1>Sign in first</h1><Link href="/owner">Go to owner sign in</Link></section></main>;const map=selected?`https://www.openstreetmap.org/export/embed.html?bbox=${selected.longitude-.008}%2C${selected.latitude-.005}%2C${selected.longitude+.008}%2C${selected.latitude+.005}&layer=mapnik&marker=${selected.latitude}%2C${selected.longitude}`:"";
return <main className="wide"><header><div><p className="eyebrow">PAWPING V7</p><h1>Tracking & alerts</h1></div><Link className="secondary linkbutton" href="/owner">Pets</Link></header>{msg&&<p className="result wrap">{msg}</p>}<section className="v7grid"><div><div className="sectionTitle"><h2>Location history</h2><button className="secondary fit" onClick={csv}>Export CSV</button></div>{selected&&<iframe className="bigmap" title="location" src={map}/>}<div className="tableWrap"><table><thead><tr><th>Pet</th><th>Source</th><th>Time</th><th></th></tr></thead><tbody>{events.map(x=><tr key={x.id}><td>{x.cats?.name}</td><td>{x.source}</td><td>{new Date(x.recorded_at).toLocaleString()}</td><td><button className="secondary tiny" onClick={()=>setSelected(x)}>Map</button></td></tr>)}</tbody></table></div></div><aside><section className="panel compact"><h2>Create geofence</h2><form onSubmit={saveFence}><label>Pet</label><select value={fence.cat_id} onChange={e=>setFence({...fence,cat_id:e.target.value})}>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><label>Name</label><input value={fence.name} onChange={e=>setFence({...fence,name:e.target.value})}/><label>Latitude</label><input type="number" step="any" required value={fence.latitude} onChange={e=>setFence({...fence,latitude:e.target.value})}/><label>Longitude</label><input type="number" step="any" required value={fence.longitude} onChange={e=>setFence({...fence,longitude:e.target.value})}/><label>Radius in metres</label><input type="number" min="25" required value={fence.radius_m} onChange={e=>setFence({...fence,radius_m:e.target.value})}/><button>Save geofence</button></form></section></aside></section><section><h2>GPS devices</h2><div className="cards">{cats.map(c=><article className="petCard" key={c.id}><h3>{c.name}</h3><button className="full" onClick={()=>device(c)}>Create secure device token</button></article>)}</div><div className="cards spaced">{devices.map(d=><article className="petCard" key={d.id}><h3>{d.name}</h3><p>{d.cats?.name}</p><p className="muted">Last seen: {d.last_seen_at?new Date(d.last_seen_at).toLocaleString():"Never"}</p><p className="muted">Battery: {d.battery_percent??"-"}%</p></article>)}</div></section><section><h2>Alert center</h2><div className="cards one">{alerts.map(a=><article className={`petCard ${a.read_at?"":"unread"}`} key={a.id}><b>{a.title}</b><p>{a.body}</p><small>{new Date(a.created_at).toLocaleString()}</small>{!a.read_at&&<button className="secondary full" onClick={()=>read(a.id)}>Mark read</button>}</article>)}</div></section></main>}
