import {useEffect,useState} from "react";import Link from "next/link";import {supabase,isConfigured} from "../lib/supabase";
const empty={name:"",age:"",color:"",temperament:"",health_note:"",photo_url:"",status:"safe"};
export default function Owner(){const [session,setSession]=useState(null),[email,setEmail]=useState(""),[sent,setSent]=useState(false),[cats,setCats]=useState([]),[reports,setReports]=useState([]),[form,setForm]=useState(empty),[selected,setSelected]=useState(""),[msg,setMsg]=useState("");
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load()},[session]);
 async function load(){const {data:c,error}=await supabase.from("cats").select("*").order("created_at",{ascending:false});if(error){setMsg(error.message);return}setCats(c||[]);const {data:r,error:re}=await supabase.from("finder_reports").select("id,cat_id,latitude,longitude,accuracy_m,message,created_at,cats(name)").order("created_at",{ascending:false});setReports(r||[]);if(re)setMsg(re.message)}
 async function login(e){e.preventDefault();const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin+"/owner"}});setMsg(error?error.message:"");if(!error)setSent(true)}
 async function save(e){e.preventDefault();const payload={...form,owner_id:session.user.id,public_token:crypto.randomUUID().replaceAll("-","").slice(0,20)};const {error}=await supabase.from("cats").insert(payload);setMsg(error?error.message:"Pet created");if(!error){setForm(empty);load()}}
 async function updateStatus(cat,status){const {error}=await supabase.from("cats").update({status}).eq("id",cat.id);setMsg(error?error.message:"Status updated");if(!error)load()}
 async function remove(cat){if(!confirm(`Delete ${cat.name}? Reports will also be deleted.`))return;const {error}=await supabase.from("cats").delete().eq("id",cat.id);setMsg(error?error.message:"Pet deleted");if(!error)load()}
 if(!isConfigured)return <main className="shell"><section className="panel"><h1>Setup missing</h1></section></main>;
 if(!session)return <main className="shell"><section className="panel auth"><div className="logo">🐾</div><h1>Owner sign in</h1><p className="muted">Receive a secure magic link by email.</p><form onSubmit={login}><label>Email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><button>{sent?"Send another link":"Send magic link"}</button></form>{sent&&<p className="result">Check your email and open the PawPing sign-in link.</p>}{msg&&<p className="error">{msg}</p>}</section></main>;
 return <main className="wide"><header><div><p className="eyebrow">OWNER DASHBOARD</p><h1>PawPing</h1></div><button className="secondary" onClick={()=>supabase.auth.signOut()}>Sign out</button></header>{msg&&<p className="result">{msg}</p>}<div className="dashboard"><section><div className="sectionTitle"><h2>My pets</h2><span>{cats.length}</span></div><div className="cards">{cats.map(c=><article className="petCard" key={c.id}><div className="petTop"><div className="avatar">{c.photo_url?<img src={c.photo_url} alt=""/>:"🐈"}</div><div><h3>{c.name}</h3><span className={`pill ${c.status}`}>{c.status}</span></div></div><p className="muted">{c.color||"No color"} · {c.age||"No age"}</p><div className="qrbox"><small>QR LINK</small><code>{`${typeof window!=="undefined"?window.location.origin:""}/c/${c.public_token}`}</code></div><div className="row"><a className="primary small" href={`/c/${c.public_token}`} target="_blank">Open profile</a><button className="secondary small" onClick={()=>navigator.clipboard.writeText(`${window.location.origin}/c/${c.public_token}`)}>Copy link</button></div><div className="row"><button className="secondary small" onClick={()=>updateStatus(c,c.status==="missing"?"safe":"missing")}>Mark {c.status==="missing"?"safe":"missing"}</button><button className="danger small" onClick={()=>remove(c)}>Delete</button></div></article>)}{!cats.length&&<div className="empty">No pets yet. Create the first profile.</div>}</div></section><aside><section className="panel compact"><h2>Add a pet</h2><form onSubmit={save}>{[["name","Name *"],["age","Age"],["color","Color"],["temperament","Temperament"],["health_note","Health note"],["photo_url","Photo URL"]].map(([k,l])=><div key={k}><label>{l}</label><input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} required={k==="name"}/></div>)}<label>Status</label><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="safe">Safe</option><option value="missing">Missing</option></select><button>Create pet and QR link</button></form></section></aside></div><section className="reports"><div className="sectionTitle"><h2>Finder reports</h2><span>{reports.length}</span></div><div className="tableWrap"><table><thead><tr><th>Pet</th><th>Message</th><th>Time</th><th>Accuracy</th><th>Location</th></tr></thead><tbody>{reports.map(r=><tr key={r.id}><td>{r.cats?.name||"Pet"}</td><td>{r.message||"—"}</td><td>{new Date(r.created_at).toLocaleString()}</td><td>{r.accuracy_m?`${Math.round(r.accuracy_m)} m`:"—"}</td><td><a href={`https://www.google.com/maps?q=${r.latitude},${r.longitude}`} target="_blank">Open map</a></td></tr>)}</tbody></table>{!reports.length&&<div className="empty">No finder reports yet.</div>}</div></section></main>}
